# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-07 17:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('img', models.ImageField(default='images/clothes/default.png', upload_to='images/clothes/')),
            ],
        ),
        migrations.CreateModel(
            name='Eye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('img', models.ImageField(default='images/eye/default.png', upload_to='images/eye/')),
            ],
        ),
        migrations.CreateModel(
            name='Hair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('img', models.ImageField(default='images/hair/default.png', upload_to='images/hair/')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='clothes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.Clothes'),
        ),
        migrations.AddField(
            model_name='character',
            name='eye',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.Eye'),
        ),
        migrations.AddField(
            model_name='character',
            name='hair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.Hair'),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
