# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-08 05:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0002_group_registrationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rpg.Group'),
        ),
        migrations.AddField(
            model_name='registrationcode',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
