# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-27 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0002_auto_20180127_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='bossmonster',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rpg.Skill'),
        ),
    ]
