# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-08 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0003_auto_20180108_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='clothes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rpg.Clothes'),
        ),
        migrations.AlterField(
            model_name='character',
            name='eye',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rpg.Eye'),
        ),
        migrations.AlterField(
            model_name='character',
            name='hair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rpg.Hair'),
        ),
    ]
