# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0003_bossmonster_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bossbattle',
            name='ready_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
