# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0004_bossbattle_ready_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finalbossbattle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ally_health', models.IntegerField(default=100)),
                ('turn', models.IntegerField(default=0)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rpg.Character')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rpg.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='Finalbossbattlemanager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enemy_health', models.IntegerField(default=10000000)),
                ('turn', models.IntegerField(default=0)),
                ('state', models.CharField(default='before', max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.Group')),
            ],
        ),
    ]
