# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-08 07:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rpg', '0004_auto_20180108_0535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ally_health', models.IntegerField(default=100)),
                ('enemy_health', models.IntegerField(default=100)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('img', models.ImageField(default='images/monster/default.png', upload_to='images/monster/')),
                ('exp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('damage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.Type'),
        ),
        migrations.AddField(
            model_name='monster',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.Skill'),
        ),
        migrations.AddField(
            model_name='monster',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.Type'),
        ),
        migrations.AddField(
            model_name='battle',
            name='monster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.Monster'),
        ),
    ]
