# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0004_bossbattle_ready_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillbook',
            name='finder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rpg.Character'),
        ),
    ]
