# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 06:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0005_finalbossbattle_finalbossbattlemanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalbossbattlemanager',
            name='group',
        ),
    ]
