# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-08 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0006_auto_20180108_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='skill1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill1', to='rpg.Skill'),
        ),
        migrations.AddField(
            model_name='character',
            name='skill2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill2', to='rpg.Skill'),
        ),
        migrations.AddField(
            model_name='character',
            name='skill3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill3', to='rpg.Skill'),
        ),
        migrations.AddField(
            model_name='character',
            name='skill4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill4', to='rpg.Skill'),
        ),
        migrations.AddField(
            model_name='monster',
            name='death_dialog',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='dialog1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='dialog2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='dialog3',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
