# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0006_remove_finalbossbattlemanager_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalbossbattle',
            name='frusted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='finalbossbattle',
            name='helper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='helper', to='rpg.Character'),
        ),
        migrations.AlterField(
            model_name='finalbossbattle',
            name='character',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='character', to='rpg.Character'),
        ),
    ]
