# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0008_remove_finalbossbattle_skill'),
        ('rpg', '0005_auto_20180129_0227'),
    ]

    operations = [
    ]
