# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0008_auto_20180108_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='health',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='battle',
            name='enemy_health',
            field=models.IntegerField(default=0),
        ),
    ]
