# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0009_auto_20180108_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonsterBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=20, null=True)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion', to='rpg.Character')),
                ('finder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finder', to='rpg.Character')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.Group')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.Monster')),
            ],
        ),
    ]
