# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-09 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0010_auto_20180201_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clotheshave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.Clothes')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Eyehave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.Eye')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Hairhave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.Group')),
                ('hair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.Hair')),
            ],
        ),
    ]
