# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-09 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0011_clotheshave_eyehave_hairhave'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='is_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eye',
            name='is_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hair',
            name='is_event',
            field=models.BooleanField(default=False),
        ),
    ]
