# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-13 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0012_contain'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='limit',
            field=models.IntegerField(default=0),
        ),
    ]
