# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-13 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0013_skill_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skillbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.Character')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.Group')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.Skill')),
            ],
        ),
    ]
