# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-13 12:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0014_skillbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='dialog4',
            field=models.CharField(default='dialog4', max_length=50),
        ),
        migrations.AddField(
            model_name='monster',
            name='dialog5',
            field=models.CharField(default='dialog5', max_length=50),
        ),
        migrations.AddField(
            model_name='monster',
            name='drop_rate',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='monster',
            name='death_dialog',
            field=models.CharField(default='death dialog', max_length=50),
        ),
        migrations.AlterField(
            model_name='monster',
            name='dialog1',
            field=models.CharField(default='dialog1', max_length=50),
        ),
        migrations.AlterField(
            model_name='monster',
            name='dialog2',
            field=models.CharField(default='dialog2', max_length=50),
        ),
        migrations.AlterField(
            model_name='monster',
            name='dialog3',
            field=models.CharField(default='dialog3', max_length=50),
        ),
    ]
