# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0015_auto_20180210_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='bossbattlemanager',
            name='dialognum',
            field=models.IntegerField(default=1),
        ),
    ]
