# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0016_bossbattlemanager_dialognum'),
    ]

    operations = [
        migrations.AddField(
            model_name='bossbattlemanager',
            name='skill1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill0001', to='rpg.Skill'),
        ),
        migrations.AddField(
            model_name='bossbattlemanager',
            name='skill2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill0002', to='rpg.Skill'),
        ),
    ]
