# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0017_auto_20180210_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='kill',
            field=models.IntegerField(default=0),
        ),
    ]
