# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-10 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0018_group_kill'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='battletime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
