# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0018_combination'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedCombination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.Group')),
                ('skill001', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill001', to='rpg.Skill')),
                ('skill002', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill002', to='rpg.Skill')),
            ],
        ),
    ]
