# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0022_auto_20180115_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='turn',
            field=models.IntegerField(default=0),
        ),
    ]
