# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0023_battle_turn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Have',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.Character')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.Skill')),
            ],
        ),
    ]
