# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-17 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0024_have'),
    ]

    operations = [
        migrations.AlterField(
            model_name='have',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
