# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-17 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0025_auto_20180117_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contain',
            name='character',
        ),
        migrations.RemoveField(
            model_name='contain',
            name='skill',
        ),
        migrations.DeleteModel(
            name='Contain',
        ),
    ]
