# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0026_auto_20180117_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bossbattle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ally_health', models.IntegerField(default=100)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rpg.Character')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='Bossbattlemanager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enemy_health', models.IntegerField(default=100000)),
                ('turn', models.IntegerField(default=0)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bossmonster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('img', models.ImageField(default='images/monster/default.png', upload_to='images/monster/')),
                ('health', models.IntegerField(default=100000)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.Map')),
            ],
        ),
        migrations.AddField(
            model_name='bossbattlemanager',
            name='bossmonster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.Bossmonster'),
        ),
        migrations.AddField(
            model_name='bossbattlemanager',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.Group'),
        ),
    ]
