# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0028_auto_20180122_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='bossbattle',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
