# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0029_bossbattle_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bossbattlemanager',
            name='state',
            field=models.CharField(default='waiting', max_length=20),
        ),
    ]
