# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0031_auto_20180122_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='bossbattlemanager',
            name='banned_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bossbattlemanager',
            name='boss_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bossbattlemanager',
            name='redo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bossmonster',
            name='damage',
            field=models.IntegerField(default=10),
        ),
    ]
