# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0032_auto_20180122_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bossmonsterbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bossmonster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.Bossmonster')),
                ('grade', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rpg.Grade')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpg.Group')),
            ],
        ),
    ]
