# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0033_auto_20180126_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bossbattlemanager',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
