# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0034_auto_20180126_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='bossbattlemanager',
            name='bossskill',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
