# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0036_bossgrade'),
        ('rpg', '0033_bossmonsterbook'),
    ]

    operations = [
    ]
