# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0037_bossmonsterbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bossmonsterbook',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rpg.Bossgrade'),
        ),
    ]
