# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-26 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpg', '0038_auto_20180126_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='boss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='improvise',
            field=models.BooleanField(default=False),
        ),
    ]
